### ISSUE TITLE
'NoneType' object has no attribute 'copy'

### ISSUE THREAD

**Issue by avnbad** [akmamun/multi-threading-camera-stream#1]
How to handle this None Type error we get 'NoneType' object has no attribute 'copy'

**Comment by mrxmamun** [comment]
What's your camera source? check it its happened if camera frame not found.

**Comment by akmamun** [comment]
What's your camera source? it's may happen if the camera not found.

**Comment by avnbad** [comment]
Camera source is an IP camera and the camera stream is acquired using RTSP.
Camera stream is properly working until we encountered None frame. Then class throw "Nonetype object has no attribute copy error"

**Comment by mrxmamun** [comment]
Could you write the camera source as a string in camera.py file?  if the error is ` 'NoneType' object has no attribute 'copy'`  this error means your camera can't work.

**Comment by mrxmamun** [comment]
Could you write the camera source as a string in camera.py file? if the error is 'NoneType' object has no attribute 'copy' this means your camera can't work.

**Comment by akmamun** [comment]
Could you write the camera source as a string in camera.py file? if the error is `'NoneType' object has no attribute 'copy' `this error means your camera can't work.

**Comment by avnbad** [comment]
Is this error can be handled through try or except like this 
def read(self):
        try:
            self.read_lock.acquire()
            frame = self.frame.copy()
            self.read_lock.release()
            return frame
        except:
            pass
or

if self.frame is None: 
     break

**Comment by akmamun** [comment]
yeah, this may handle None type frame.

**Comment by avnbad** [comment]
Thanks for responding
